version: 1.0.{build}
branches:
  only:
  - master
  - ci/all
  - ci/appveyor

environment:
  ASIOSDK: C:\projects\ASIOSDK2.3
  OWNCLOUDPASS:
    secure: WMAPpQn8AuyEvSENma5wNQhsEYAxz87oJhgxiLRvtXg=
  OWNCLOUDUSER:
    secure: hGxoNrHEyHNyt12RjZ9cOQ==
  image: Visual Studio 2015
  matrix:
    - platform: Win32
      configuration: Release32
    - platform: x64
      configuration: Release
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
  - ps: |
      echo "submodule"
      git submodule -q update --init --recursive
      cd C:\projects\lgml\third_party\libpd
      cmake . -G "%generator%" -DPD_MULTI:BOOL=ON -DPD_UTILS=OFF -DMSVC_STATIC_RUNTIME=ON -DMSVC_PTHREAD_LIB="pthread.lib"
      msbuild C:\projects\lgml\third_party\libpd\libpd.sln /p:Configuration=Release /m:4
      cd C:\projects\lgml\third_party\rubberband
      echo 'building rubberband'
      msbuild C:\projects\lgml\third_party\rubberband\rubberband-library.sln /p:Configuration=Release /m:4
      echo 'dowloading JUCE'
      wget https://codeload.github.com/WeAreROLI/JUCE/zip/master -OutFile JUCE.zip
      7z x JUCE.zip -o"C:\projects" -y
      Rename-Item -path ‘C:\projects\JUCE-master’ -newName ‘JUCE’
      echo 'downloading ASIOSDK'
      wget http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip -OutFile ASIO_SDK.zip
      7z x ASIO_SDK.zip -o"C:\projects" -y


# after_build:
#   cmd: 7z a %APPVEYOR_BUILD_FOLDER%\LGML_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\%PLATFORM%\%CONFIGURATION%\App\*.exe

deploy_script:
  - pip install future requests
  - cmd: python %APPVEYOR_BUILD_FOLDER%\Scripts\buildScript.py --configure --os=windows --configuration=%CONFIGURATION% --arch=%PLATFORM%  --exportpath=%APPVEYOR_BUILD_FOLDER%
  - cmd: python %APPVEYOR_BUILD_FOLDER%\Scripts\buildScript.py --package --export

artifacts:
  - path: '*.zip'

build:
  project: Builds/VisualStudio2015/LGML.sln
  verbosity: minimal
  parallel: true