version: 1.0.{build}
branches:
  only:
  - feature/ci
environment:
  ASIOSDK: C:\projects\ASIOSDK2.3
  matrix:
    - platform: Win32
      configuration: Debug_32bit
    - platform: x64
      configuration: Debug

before_build:
  ps: |
    echo "submodule"
    git submodule -q update --init --recursive --remote
    cd C:\projects\lgml\third_party\rubberband
    echo 'build rubberband'
    ls C:\projects\lgml\third_party\rubberband
    git remote -v
    msbuild C:\projects\lgml\third_party\rubberband\rubberband-library.sln /p:Configuration=Debug /m:4
    wget https://codeload.github.com/WeAreROLI/JUCE/zip/master -OutFile JUCE.zip
    7z x JUCE.zip -o"C:\projects" -y
    Rename-Item -path ‘C:\projects\JUCE-master’ -newName ‘JUCE’
    wget http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip -OutFile ASIO_SDK.zip
    7z x ASIO_SDK.zip -o"C:\projects" -y

build:
  project: Builds/VisualStudio2015/LGML.sln
  verbosity: minimal