version: 1.0.{build}
branches:
  only:
  - master
  - ci/all
  - ci/appveyor

environment:
  ASIOSDK: C:\projects\ASIOSDK2.3
  OWNCLOUDPASS:
    secure: WMAPpQn8AuyEvSENma5wNQhsEYAxz87oJhgxiLRvtXg=
  OWNCLOUDUSER:
    secure: hGxoNrHEyHNyt12RjZ9cOQ==
  image: Visual Studio 2015
  matrix:
    - platform: Win32
      configuration: Release32
      PTHREAD: x86
      COMPILER: "Visual Studio 14 2015"
    - platform: x64
      configuration: Release
      PTHREAD: x64
      COMPILER: "Visual Studio 14 2015 Win64"

install:
    - echo "submodule"
    - git submodule -q update --init --recursive
    - set basepd="C:\\projects\\lgml\\third_party\\libpd"
    - cd "%basepd%"
    - curl ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
    - 7z x -opthreads pthreads.zip  Pre-built.2/dll Pre-built.2/lib Pre-built.2/include
    - mkdir build
    - mkdir build\msvcstatic
    - mkdir build\msvcdll
    - set pthreaddir="%basepd%\\pthreads\\Pre-built.2"
    # - set builddir="%APPVEYOR_BUILD_FOLDER%\\build\\msvcstatic"
    - cd "%pthreaddir%\\include" && copy "*.h" "%basepd%\\pure-data\\src"
    - cd "%pthreaddir%\\lib\\%PTHREAD%" && copy "pthreadVC2.lib" "%basepd%\\build\\msvcstatic\\pthreadVC2.lib"
    - cd "%pthreaddir%\\lib\\%PTHREAD%" && copy "pthreadVC2.lib" "%basepd%\\build\\msvcdll\\pthreadVC2.lib"

before_build:
    - cd C:\projects\lgml\third_party\libpd\build\msvcstatic
    - cmake ../.. -G "%COMPILER%" -DPD_MULTI:BOOL=ON -DPD_UTILS=OFF -DMSVC_STATIC_RUNTIME=ON -DMSVC_PTHREAD_LIB="pthread.lib"
    - msbuild libpd.sln /t:libpdstatic /p:Configuration=Release /p:Platform=%PLATFORM% /m:4
    - cd C:\projects\lgml\third_party\rubberband
    - echo 'building rubberband'
    - msbuild C:\projects\lgml\third_party\rubberband\rubberband-library.sln /p:Configuration=Release /m:4
    - echo 'dowloading JUCE'
    - curl https://codeload.github.com/WeAreROLI/JUCE/zip/master -o JUCE.zip
    - 7z x JUCE.zip -o"C:\projects" -y
    - copy "C:\projects\JUCE-master" "JUCE"
    - echo 'downloading ASIOSDK'
    - curl http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip -o ASIO_SDK.zip
    - 7z x ASIO_SDK.zip -o"C:\projects" -y


# after_build:
#   cmd: 7z a %APPVEYOR_BUILD_FOLDER%\LGML_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\%PLATFORM%\%CONFIGURATION%\App\*.exe

deploy_script:
  - pip install future requests
  - cmd: python %APPVEYOR_BUILD_FOLDER%\Scripts\buildScript.py --configure --os=windows --configuration=%CONFIGURATION% --arch=%PLATFORM%  --exportpath=%APPVEYOR_BUILD_FOLDER%
  - cmd: python %APPVEYOR_BUILD_FOLDER%\Scripts\buildScript.py --package --export

artifacts:
  - path: '*.zip'

build:
  project: Builds/VisualStudio2015/LGML.sln
  verbosity: minimal
  parallel: true