cache:
    paths:
    - ~/Dev
    - ~/SDK
job:
  stage: build
  tags:
    - osx
    - lgml
  script:
    - "echo installDeps"
    - "sh src/LGML/Scripts/osx/installDeps.sh;"
    - "python src/LGML/Scripts/buildScript.py --build --beta"
