version: 2
jobs:
  build:
    working_directory: ~/LGML
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: install LGML dependencies
          command: |
            apt-get -qq update
            apt-get install -y git
            git submodule update --init --recursive --remote
            sh Scripts/linux/installDeps.sh && sh Scripts/linux/installDevDeps.sh
      - run:
          name: build LGML
          command: |
            python Scripts/buildScript.py --build --beta --os=linux;
      - run:
          name: package LGML
          command: |
            mkdir -p /tmp/build
            python Scripts/buildScript.py --package --beta --exportpath=/tmp/build/ --os=linux --configuration=Ubuntu;
            ldd /root/LGML/Builds/LinuxMakefile/build/LGML
      - store_artifacts:
          path: /tmp/build/

      - run:
          name: build LGML32
          command: |
            apt-get install -y g++-multilib
            dpkg --add-architecture i386
            apt-get update
            export LGML_TARGET_ARCH=i386
            sh Scripts/linux/installDeps.sh && sh Scripts/linux/installDevDeps.sh
            python Scripts/buildScript.py --build --beta --os=linux --configuration=Ubuntu32;
      - run:
          name: package LGML32
          command: |
            mkdir -p /tmp/build32
            python Scripts/buildScript.py --package --beta --exportpath=/tmp/build32/ --os=linux --configuration=Ubuntu32;
      - store_artifacts:
          path: /tmp/build32/

general:
  branches:
    only:
      - master
      - develop
      - feature/ci
