version: 2
jobs:
  build:
    working_directory: ~/LGML
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: install LGML dependencies
          command: |
            apt-get install -y git
            git submodule update --init --recursive --remote
            sh Scripts/linux/installDeps.sh && sh Scripts/linux/installDevDeps.sh
      - run:
          name: build LGML
          command: |
            python Scripts/buildScript.py --build --beta --os=linux;



general:
  branches:
    only:
      - master
      - develop
      - feature/ci
