version: 2
jobs:
  build:
    working_directory: ~/LGML
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run:
          name: install LGML dependencies
          command: |
          sh Scripts/linux/installDeps.sh && sh Scripts/linux/installDevDeps.sh;
      - run:
          name: build LGML
          command: |
          python Scripts/buildScript.py --build --beta --os=linux;



general:
  branches:
    only:
      - master
      - develop
      - feature/ci



